### ISSUE TITLE
parse plot info error causing plot opening failure

### ISSUE THREAD

**Issue by Goldensoap** [Chia-Network/bladebit#223]
Debain 11.05/rockylinux9 x86_64
chia-blockchian(gui) 1.6.0
bladebit 1.2.4

I initially used the compiled bladebit on Rockylinux9 and found this error, then switched to Debian to use the bladebit that comes with the GUI, but still had the same error

I've looked at other content related to open file failures and didn't find anything similar.

here is chia-blockchian debug log , it looks like a memo miscalculation.
```
2022-10-14T23:48:57.469 harvester chia.plotting.manager   : ERROR    Failed to open file /home/plot/buffer/plot-k32-2022-10-14-23-36-a94db56f70dbafef3a13be5278e2313a556103a3150ad114d1fc5c26f0769b53.plot. Relic library error Traceback (most recent call last):
  File "chia/plotting/manager.py", line 288, in process_file
  File "chia/plotting/cache.py", line 56, in from_disk_prover
  File "chia/plotting/util.py", line 154, in parse_plot_info
ValueError: Relic library error
```
Is there a better way for me to debug? or did i miss something？

**Comment by Goldensoap** [comment]
I tried to start madmax and chia proof of space with the same parameters and both results are correct, very strange

**Comment by Goldensoap** [comment]
Some plot will also give the following error

G1 element is invalid Traceback (most recent call last):
  File "chia/plotting/manager.py", line 288, in process_file
  File "chia/plotting/cache.py", line 56, in from_disk_prover
  File "chia/plotting/util.py", line 154, in parse_plot_info
ValueError: G1 element is invalid

**Comment by Goldensoap** [comment]
I have checked that the farmer public key and the pool contract address are correct ，same as what I use in madmax......so why?

**Comment by Goldensoap** [comment]
I tried using --pool-key instead of --pool-contract and it works fine. I'm guessing that the error is related to the contract address, I'll do more testing

**Comment by Goldensoap** [comment]
https://github.com/Chia-Network/bladebit/issues/122#issuecomment-939115160
#122 
very very strange ，if anyone has encountered a similar problem, please try the above method as well.

**Comment by harold-b** [comment]
I’ll have a look.  Remember that pool key will make OG plots
