### ISSUE TITLE
[BUG] Bladebit Crashed 

### ISSUE THREAD

**Issue by AFCzzi** [Chia-Network/bladebit#349]
Can anyone help? I ran the plotter from chia GUI and it crashed shortly after I started plotting, the Bladebit plotter crashed on server with enough RAMs showing the following error log:
```shell
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x00000196D0E92780> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x00000196D0F1C390> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x00000196D0F1C390> still has pending operation at deallocation, the process may crash
Creating 1 plots:
 Output path           : A:\AA
 Thread count          : 48
 Warm start enabled    : false
 Farmer public key     : 8cd79c163xxxxxxxxxxxxxxb4b60626005a870d3ba3c4cf42b06cbb6b3a80d24f35d73ab6f09c69ed98328c1c0f2c562
 Pool public key       : 8a6e72440xxxxxxxxxxxx36222e93824da031e26e1b08b0ab7125206a99eed50ff56bef5b1aab19cf1b2e93683a3d989

Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x00000196D0E92390> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x00000196D0E92390> still has pending operation at deallocation, the process may crash
```

**Comment by jmhands** [comment]
we will need full system configuration, bladebit version, etc. to debug

**Comment by esaung** [comment]
which version of the chia client are you running?

**Comment by jmhands** [comment]
closing, stale and not enough info to debug
